### ISSUE TITLE
Widgets do not pop up on desktop

### ISSUE THREAD

**Issue by W1ntrexx** [project-oneui/Galaxy-Widgets#1]
Downloaded the Samsung Settings App, installed perfectly fine. But toggling the switches for the switches seem to do nothing. Restarted already, did do anything. 
![Screenshot 2023-10-23 190256](https://github.com/project-oneui/Samsung-Widgets/assets/103531934/fc32f9ce-aee8-499e-b652-2b5de963de60)

**Comment by thisisrandomguys** [comment]
Samsung Widgets app has to be run one time before using Samsung Settings ( Samsung Widgets wasn't installed )
