### ISSUE TITLE
Can't move widgets

### ISSUE THREAD

**Issue by pedrocp04** [project-oneui/Galaxy-Widgets#3]
I can't move or resize the widgets

I clic everywhere and just can't, not even with the setings app

 - OS: Windows 11

**Comment by thisisrandomguys** [comment]
Widget Sizes have to be changed in the config file. To find this file: Press Windows + R > Type appdata and press enter > Local > Galaxy-Widgets > WidgetStates.json.

The positioning can be changed in WidgetPosiontions.json.

Could you please share a video of your problem with the positioning so I can look into it? Thanks!

**Comment by thisisrandomguys** [comment]
Just wanted to add that I am working on a user friendly system for the widget sizes.
