### ISSUE TITLE
can't add some widgets

### ISSUE THREAD

**Issue by pedrocp04** [project-oneui/Galaxy-Widgets#4]
Can't add some widgets, like music widget or the notes widget, and the battery widget isn't showing my cellphone battery stats and have this message everytime I try to add the calendar widget

![Captura de tela 2024-01-10 113035](https://github.com/project-oneui/Galaxy-Widgets/assets/81369076/0b44fd61-45cc-43bf-a8b3-5ed62617e8e2)

 - OS: windows 11

I love this project ! and I see a great future in this ! keep this up !

**Comment by thisisrandomguys** [comment]
Hey, the music widget could be under another widget so maybe check that. Else look under %LocalAppdata%/Galaxy-Widgets in the widgetstates.json if show for the music widget is to be true. I'm gonna look into the calendar widget when im at home. For the Battery widget you have to follow the tutorial, if you did and it didnt work then check the IP and Port. Oh and let the widget app run till the phone lost 1% in battery so it it'll send the battery percentage to the app.
